### PR TITLE
postgres error CREATE SCHEMA IF NOT EXISTS n8n 

### PR DESCRIPTION
**Pull request by eyalfishler**
fixed an issue  with 
calling CREATE SCHEMA IF EXISTS causes error on postgres server 
 ```
 sql_error_code = 00000 time_ms = "2024-07-20 04:48:15.846 UTC" pid="303954" proc_start_time="2024-07-20 04:48:14 UTC" session_id="669b418e.4a352" vtid="2/271031" tid="0" log_line="14" database="XXXXX" connection_source="X.Y.Z.M(64744)" user="YYYYYYY" application_name="[unknown]" LOG:  statement: CREATE SCHEMA IF NOT EXISTS n8n
 ```

### CODE REVIEW

**Comment by eyalfishler** [comment]
postgres 15.7

**Comment by eyalfishler** [comment]
its in the log of the postgres server itself not the web or worker threads

**Comment by netroy** [comment]
This looks like a harmless warning in postgres logs. Also, I'm not able o reproduce this. What version of postgres are you using? and have you changed any logging related settings?

**Comment by tomi** [comment]
As per [Postgres error codes](https://www.postgresql.org/docs/current/errcodes-appendix.html), code `00000` indicates `successful_completion` and the log level is `LOG` which means it's informational. So it's Postgres logging that a schema was created. It's not a bug or error, but rather everything working normally.

**Comment by eyalfishler** [comment]
i dont see why not avoid this error which is spamming the logs with a check for " BEGIN IF NOT EXISTS " as in the PR

**Comment by eyalfishler** [comment]
also if you can review the fix the gulp file so the project compiles

**Comment by netroy** [comment]
> i dont see why not avoid this error

but it clearly says `sql_error_code = 00000`, which postgres docs say is not an error. 

Do you have perhaps more verbose logging enabled on your postgres server?
I tried reproducing this on various postgres servers and containers we have, and could not get this line to be logged.

Since we are not even able to reproduce this (let alone this not being an error in the first place), the only argument to merge this PR is that it exists. Which IMO is not a valid argument.

> also if you can review the fix the gulp file so the project compiles
It's not great that upstream is still stuck with an old tool like gulp, but so far we have had no issues with compilation.
We do `pnpm install`, followed by `pnpm compile && pnpm package`, and that creates a valid package in the `build` folder.

Since we do not know if or how long we plan to keep using this fork of typeorm, we do not want to spend any more time or resources on this repo.

**Comment by lossendae** [comment]
I have the same issue on my end, our devops had to silence our surveillance log tool on our pg instance.

This is problematic:
- We host other application on this pg server
- The log keeps on growing indefinitely (1 message every 2 minutes)

This may be linked to the fact that we're using PGPOOL. Excerpt of the logs:

```
Mar  7 15:55:48 our-db pgpool: 2025-03-07 15:55:48: pid XXXX: LOG:  pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: XXXX statement: "CREATE SCHEMA IF NOT EXISTS n8n" message: "schema "n8n" already exist
Mar  7 15:55:50 our-db pgpool: 2025-03-07 15:55:50: pid XXXX: LOG:  pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: XXXX statement: "CREATE SCHEMA IF NOT EXISTS n8n" message: "schema "n8n" already exist
Mar  7 15:55:52 our-db pgpool: 2025-03-07 15:55:52: pid XXXX: LOG:  pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: XXXX statement: "CREATE SCHEMA IF NOT EXISTS n8n" message: "schema "n8n" already exist
```

The schema does already exist, is it normal that n8n keep on trying to create it ?

**Pull request closed without merging**
